[package]
name = "monkey-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.79"
byteorder = "1.5.0"
clap = { version = "4.4.12", features = ["derive"] }

[lib]
path = "lib/mod.rs"

[[bin]]
name = "monkey"
path = "src/main.rs"
